config/routes.rb
Blog::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users
  devise_for :admins, :controllers => { :sessions => "admins/sessions" }

  resources :comments
  resources :profiles
  resources :articles do

    member do
      post 'comment'
    end
  end



  get "/home", to: 'pages#home'

  get "/news", to: 'pages#news'

  get "/about", to: 'pages#about'

  get "/books", to: 'pages#books'

  root :to => 'pages#home'
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessor :sufix, :first_name, :last_name
  attr_accessible :avatar, :name, :sufix, :first_name, :last_name


  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"

  belongs_to :user

  ["sufix","first_name","last_name"].each_with_index do |name,index|
    define_method "#{name}" do
      self.name.split(" ")[index]     #split an array(name) by index[0,1,2]
    end
  end

  def has_attached_file(name, options = {})
    HasAttachedFile.define_on(self, name, options)
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
before_filter :authenticate_user!
before_filter :find_profile, except: [:new,:create, :index ]

def new
  @title = "Profile"
  @profile = Profile.new
end

def show

end

def create
  suffix = params[:sufix]
  f_n = params[:first_name]
  l_n = params[:last_name]
  a=params[:profile]
  a.merge!({:name => "#{suffix} #{f_n} #{l_n}"})
  #@avatars= @profile.avatars
  @profile = Profile.new(a)
  if @profile .save
    flash[:success]= "Welcome to Your Profile"                         #  Parameters: {"utf8"=>"✓", "authenticity_token"=>"KPJGSVoW2naygRG1HFKCLmOtyZdold+zyfKadUMzZcA=", "sufix"=>"miss", "first_name"=>"addf", "last_name"=>"vcvjhgjh", "user"=>{"email"=>"dfgfhgk", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Sign up"}
    redirect_to @profile
  else
    @title = "Profile"
    render 'new'
  end
end

def edit
  @title = "Edit profiles"
end

def update
  suffix = params[:profile][:sufix]
  f_n = params[:profile][:first_name]
  l_n = params[:profile][:last_name]
  a=params[:profile]
  a.delete_if{|k,v| ["sufix", "first_name", "last_name"].include?(k)}    #To control mass assignment delete params.
  a.merge!({:name => "#{suffix} #{f_n} #{l_n}"})
  if @profile.update_attributes(a)
    flash[:success] = "Profile Updated."                                            #After delete the params check the difference between create and update
    redirect_to @profile                                                               #  Parameters: {"utf8"=>"✓", "authenticity_token"=>"KPJGSVoW2naygRG1HFKCLmOtyZdold+zyfKadUMzZcA=", "user"=>{"sufix"=>"miss", "first_name"=>"addf", "last_name"=>"vcvjhgjh", "email"=>"dfgfhgk", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Sign up", "id"=>"8"}
  else
    @title = "Edit profile"
    render 'edit'
  end
end

def index
  @profile=Profile
end

end



private
def find_profile
  @profile= Profile.find(params[:id])
end

app/views/profiles/edit.html.erb
<h1> Edit Profile</h1>
<%= image_tag @profile.avatar.url %>
<%= form_for @profile, :html => { :multipart => true } do |f| %>

    <% arr = ["sufix", "first_name", "last_name"] %>

    <%= dynamic_define_fields(arr) %>

    <%= f.file_field :avatar %>

    <div class="actions">
      <%= f.submit "Update" %>
    </div>
    <%= link_to 'Show', profile_path(@profile) %>

<% end %>

app/views/profiles/new.html.erb
<%= form_for @profile do |f| %>

    <div class="field">
      <%= label_tag :sufix %> <br />     <%# f.text_field:text means object f takes data from form.But here f. is not used Because here we are using different form.And for that we are using Text_field_tag.%>
      <%= text_field_tag :sufix %>       <%# we have only one database coloum field-name, but we want to put our data as suffix,first name and last name.So we create a hash of name in model where we put suffix, first name and last name value.%>

    </div>
    <div class="field">
      <%= label_tag :first_name %> <br />
      <%= text_field_tag :first_name %>

    </div>
    <div class="field">
      <%= label_tag :last_name %> <br />
      <%= text_field_tag :last_name %>

    </div>


    <div class="field">
      <%#<%= form_for @user, :url => users_path, :html => { :multipart => true } do |form| %>
      <%= f.file_field :avatar %>
      <%#<% end %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>

 <% end %>

app/views/profiles/show.html.erb
<%= link_to 'Edit Profile', edit_profile_path(@profile) %>
<table class="profile" summary="Profile information" >
  <%= flash[:success]= "Welcome to Your Profile" %>
  <tr>
    <td class="main">

      <h1>
        <%= @profile.name %>
        <%= image_tag @profile.avatar.url(:medium) %>
      </h1>

  </td>
  </tr>
</table>