config/routes.rb
Blog::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users
  devise_for :admins, :controllers => { :sessions => "admins/sessions" }

  resources :comments
  resources :profiles
  resources :articles do

    member do
      post 'comment'
    end
  end



  get "/home", to: 'pages#home'

  get "/news", to: 'pages#news'

  get "/about", to: 'pages#about'

  get "/books", to: 'pages#books'

  root :to => 'pages#home'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body
  belongs_to :article
  has_and_belongs_to_many :users

  validates :body, :presence => true ,
            :length => { :maximum => 5000}

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @comment=Comment.paginate(:page => params[:page], per_page: 2)

  end


  def show
    @comment = Comment.find(params[:id])

  end


  def new
    @comment = Comment.new

  end


  def edit
    @comment = Comment.find(params[:id])
  end


  def create
    @commentable = find_commentable

    @comment = @commentable.comments.new
    @comment.body = params[:body]

    respond_to do |format|
      if @comment.save
        format.html { redirect_to :id => nil, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end



end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<h3>Listing comments</h3>
<%= link_to 'Index', comments_path(@comments) %>


<h4>New Comment</h4>

<%= form_tag comment_article_path, method: :post do  %>
    <p>
      <%= label_tag :body %><br />
      <%= text_area_tag :body %>
    </p>
    <p><%= submit_tag "Submit" %></p>
<% end %>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/_form.html.erb
<%= form_for @new_comment do |f| %>
    <% if @new_comment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

          <ul>
            <% @comment.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :body %><br />
      <%= f.text_area :body %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<% @comments.each do |comment| %>
    <tr>
      <td><%= comment.body %></td>
      <td><%= link_to 'Show', comment %></td>
    </tr>
<% end %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>
<%= render :partial => 'comments/form', :locals => { comment => @new_comment }  %>
<%#= render :partial => 'comments/comment', :collection => @comments, :as => :comment  %>